INSERT INTO
products(name,price,image,description,weight,quantity, featured,category_id)
VALUES
    ('Carrot', '2', 'https://halfyourplate-4kgxi1gvwldjzby.stackpathdns.com/wp-content/uploads/2015/01/CarrotsWebsite-300x226.jpg','Enjoy these jumbo carrots boiled, steamed, or stir-fried. You can also add them to your salads, soups, and stews.','2 lb',15, TRUE,1),
    ('Potato', '6', 'https://imagesvc.meredithcorp.io/v3/mm/image?q=85&c=sc&poi=face&w=2000&h=1000&url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F43%2F2021%2F02%2F25%2FGettyImages-1224918845-2000.jpg', 'These yellow potatoes add a golden hue to numerous dishes. They are great mashed, baked or roasted.','10 lb',20,FALSE,1),
    ('Tomatoes','3','https://post.healthline.com/wp-content/uploads/2020/09/tomatoes-1200x628-facebook-1200x628.jpg','Tomato are a popular choice for canning or sauces, since they do not have very many seeds. Their medium sized nature also makes them a popular choice for salads.','4 lb',25, FALSE,1),
    ('Atta','18','https://i5.walmartimages.ca/images/Large/252/433/6000200252433.jpg','Aashirvaad Atta is made from the choicest grains - heavy on the palm, golden amber in colour and hard in bite.The dough made from Aashirvaad Atta absorbs more water, hence rotis remain softer for longer.','20 lb',30,TRUE,2),
    ('Rice','18','https://m.media-amazon.com/images/I/81hM8AxwHyL._SL1500_.jpg','Basmati Rice from the Foothills of the Himalayas naturally aromatic extra-long grain and aged for flavor.','10 lb',35,TRUE,2),
    ('Toor dal','8','https://st.depositphotos.com/1767558/2351/i/950/depositphotos_23513173-stock-photo-raw-moong-dhal-in-jute.jpg','Toor Dal is a good source of vegetable protein and of dietary fibers it contain various vitamins like: thiamin, magnesium, phosphorus, potassium, copper and manganese.','4 lb',20,FALSE,2),
    ('Sunflower oil','10','https://i5.walmartimages.ca/images/Enlarge/777/255/6000202777255.jpg','Worlds number one producer of Sunflower oil.Best quality oil at the most reasonable price. Use it for frying, stewing and salad dressing.','3 L',25,FALSE,2),
    ('Chick Peas','6','http://cdn.shopify.com/s/files/1/1542/6045/products/kabulichana4lb_d65923d9-4717-40cd-b288-394e689e0264_1200x1200.png?v=1618750681','Chick Peas is one of the most versatile and used item in the family. It has a low fat content but is boosted with vegetable proteins and dietary fibers and it has an interesting content of calcium, iron and folate. It is gluten free.','4 lb',20,FALSE,2);
