INSERT INTO
products(name,price,image,description,weight,quantity, featured,category_id)
VALUES
    ('Carrot', '2', 'https://halfyourplate-4kgxi1gvwldjzby.stackpathdns.com/wp-content/uploads/2015/01/CarrotsWebsite-300x226.jpg','Enjoy these jumbo carrots boiled, steamed, or stir-fried. You can also add them to your salads, soups, and stews.','2 lb',15, TRUE,1),
    ('Potato', '6', 'https://imagesvc.meredithcorp.io/v3/mm/image?q=85&c=sc&poi=face&w=2000&h=1000&url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F43%2F2021%2F02%2F25%2FGettyImages-1224918845-2000.jpg', 'These yellow potatoes add a golden hue to numerous dishes. They are great mashed, baked or roasted.','10 lb',20,FALSE,1),
    ('Tomatoes','3','https://post.healthline.com/wp-content/uploads/2020/09/tomatoes-1200x628-facebook-1200x628.jpg','Tomato are a popular choice for canning or sauces, since they do not have very many seeds. Their medium sized nature also makes them a popular choice for salads.','4 lb',25, FALSE,1),
    ('Atta','18','https://i5.walmartimages.ca/images/Large/252/433/6000200252433.jpg','Aashirvaad Atta is made from the choicest grains - heavy on the palm, golden amber in colour and hard in bite.The dough made from Aashirvaad Atta absorbs more water, hence rotis remain softer for longer.','20 lb',30,TRUE,2),
    ('Rice','18','https://m.media-amazon.com/images/I/81hM8AxwHyL._SL1500_.jpg','Basmati Rice from the Foothills of the Himalayas naturally aromatic extra-long grain and aged for flavor.','10 lb',35,TRUE,2),
    ('Toor dal','8','https://st.depositphotos.com/1767558/2351/i/950/depositphotos_23513173-stock-photo-raw-moong-dhal-in-jute.jpg','Toor Dal is a good source of vegetable protein and of dietary fibers it contain various vitamins like: thiamin, magnesium, phosphorus, potassium, copper and manganese.','4 lb',20,FALSE,2),
    ('Sunflower oil','10','https://i5.walmartimages.ca/images/Enlarge/777/255/6000202777255.jpg','Worlds number one producer of Sunflower oil.Best quality oil at the most reasonable price. Use it for frying, stewing and salad dressing.','3 L',25,FALSE,2),
    ('Chick Peas','6','http://cdn.shopify.com/s/files/1/1542/6045/products/kabulichana4lb_d65923d9-4717-40cd-b288-394e689e0264_1200x1200.png?v=1618750681','Chick Peas is one of the most versatile and used item in the family. It has a low fat content but is boosted with vegetable proteins and dietary fibers and it has an interesting content of calcium, iron and folate. It is gluten free.','4 lb',20,FALSE,2),
    ('Gaylea - Butter', '6', 'https://www.gaylea.com/wp-content/uploads/2020/01/product-butter-EN-salted-600x335-600x335.png','You can trust Gay Lea Butter. After all its made with only two ingredients - cream and salt. Pure and preservative-free, its a delicious addition to the food you make. Use it when you cook, bake, or fry, or spread it over crunchy vegetables.','454 g',20, False,3),
    ('Free Range Eggs', '8', 'https://cdn.happyegg.com/static/happyegg_web/happyegg-frontend/dist/img/cartons/heritage/03.png','Farms free range eggs are laid by Ontario-raised laying hens that live in open concept barns, with access to outdoor pastures. They can freely roam, feed, perch, and lay their eggs in nest boxes. All Conestoga Farms free range hens are fed a vegetarian, nutrient-rich diet.','12 count',25, TRUE,3),
    ('Kraft Singles', '5', 'https://i5.walmartimages.ca/images/Enlarge/208/629/6000200208629.jpg','Kraft Singles slices are the classic cheese slice with an unmistakable taste. Kraft Singles are free of artificial flavours and colours so you can your family can feel good about eating these delicious, creamy slices. Enjoy Kraft Singles on your next grilled cheese, sandwich, or burger.','22 Slices',18, FALSE,3),
    ('Lays', '5', 'https://m.media-amazon.com/images/I/71zbm2YehpL._SL1500_.jpg','Always fresh tasting, crispy and delicious, each bag of Lays Classic® potato chips is made with specially selected potatoes and to the highest quality standards. Crispy and light tasting, Lays Classic® potato chips were designed to put a smile on everyone s face, which makes them the perfect snack to share','235GM',15, FALSE,4),
    ('bourbon', '4', 'https://m.media-amazon.com/images/I/41YiGOwGaIL._AC_SY580_.jpg','PARLE HIDE & SEEK BOURBON BISCUITS','380 gm',15, TRUE,4),
    ('Wafers', '3', 'https://www.desifoodmart.com/4286-home_default/regal-hazelnut-wafers-350g.jpg','The 3 crispy light layers of the Classic wafer with 2 layers of the finest, delicately smooth hazelnut cream.','400 gm',15, FALSE,4);